name: Swift CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: swift-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14]
    env:
      SWIFT_MODULE_CACHE_PATH: ${{ runner.temp }}/swift-module-cache
      CLANG_MODULE_CACHE_PATH: ${{ runner.temp }}/clang-module-cache
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libncursesw5-dev

      - name: Show Swift version
        run: swift --version

      - name: Build
        run: swift build

      - name: Test
        run: swift test
