name: Swift CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: swift-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14]
    env:
      SWIFT_MODULE_CACHE_PATH: ${{ github.workspace }}/.swift-module-cache
      CLANG_MODULE_CACHE_PATH: ${{ github.workspace }}/.clang-module-cache
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libncursesw5-dev libpython3-dev

      - name: Install Swift development toolchain
        shell: bash
        run: |
          set -euo pipefail
          CHANNEL=development
          if [ "$RUNNER_OS" = "macOS" ]; then
            PLATFORM=xcode
          else
            PLATFORM=ubuntu24.04
          fi

          META_FILE=$(mktemp)
          curl -sSL "https://download.swift.org/${CHANNEL}/${PLATFORM}/latest-build.yml" -o "$META_FILE"

          readarray -t SWIFT_INFO < <(python3 - <<'PY' "$META_FILE"
import sys

download = ''
download_url = ''
with open(sys.argv[1], 'r', encoding='utf-8') as handle:
    for raw_line in handle:
        line = raw_line.strip()
        if line.startswith('download:'):
            download = line.split(':', 1)[1].strip()
        elif line.startswith('download_url:'):
            download_url = line.split(':', 1)[1].strip()

if not download or not download_url:
    raise SystemExit('Failed to parse Swift snapshot metadata')

print(download)
print(download_url)
PY
          )

          DOWNLOAD="${SWIFT_INFO[0]}"
          URL="${SWIFT_INFO[1]}"

          echo "Resolved Swift snapshot: $DOWNLOAD"

          if [ "$RUNNER_OS" = "macOS" ]; then
            curl -sSL "$URL" -o swift.pkg
            sudo installer -pkg swift.pkg -target /
            TOOLCHAIN_PATH="/Library/Developer/Toolchains/${DOWNLOAD}.xctoolchain/usr/bin"
            echo "${TOOLCHAIN_PATH}" >> "$GITHUB_PATH"
            echo "TOOLCHAINS=swift" >> "$GITHUB_ENV"
          else
            curl -sSL "$URL" -o swift.tar.gz
            tar -xzf swift.tar.gz
            SNAPSHOT_DIR="${DOWNLOAD}-${PLATFORM}"
            echo "${PWD}/${SNAPSHOT_DIR}/usr/bin" >> "$GITHUB_PATH"
            if [ -n "${LD_LIBRARY_PATH:-}" ]; then
              echo "LD_LIBRARY_PATH=${PWD}/${SNAPSHOT_DIR}/usr/lib:${LD_LIBRARY_PATH}" >> "$GITHUB_ENV"
            else
              echo "LD_LIBRARY_PATH=${PWD}/${SNAPSHOT_DIR}/usr/lib" >> "$GITHUB_ENV"
            fi
          fi

          mkdir -p "$SWIFT_MODULE_CACHE_PATH" "$CLANG_MODULE_CACHE_PATH"

      - name: Show Swift version
        run: swift --version

      - name: Build
        run: swift build

      - name: Test
        run: swift test
